---
# Convor Jetpack Gear
- guid: 2715
  name_id: 43520
  description_id: 14
  icon_set_id: 1847
  slot: !Equipment None
  item_type: 1
  category: 0
  cost: 2000

# Convor Pilot Gear
- guid: 2716
  name_id: 43521
  description_id: 14
  icon_set_id: 1848
  slot: !Equipment None
  item_type: 1
  category: 0
  cost: 2000

# Kowakian Sith Robe
- guid: 3274
  name_id: 50591
  description_id: 14
  icon_set_id: 2526
  slot: !Equipment None
  item_type: 1
  category: 0
  cost: 3500

# Kowakian Jedi Robe
- guid: 3275
  name_id: 50592
  description_id: 14
  icon_set_id: 2527
  slot: !Equipment None
  item_type: 1
  category: 0
  cost: 3500

# Sarlacc Balloon
- guid: 3285
  name_id: 50612
  description_id: 14
  icon_set_id: 2575
  slot: !Equipment None
  item_type: 1
  category: 0
  cost: 12000
  members: true
