---
# Teal Starfighter
- guid: 49
  name_id: 80
  description_id: 14
  icon_set_id: 690
  slot: !Equipment None
  item_type: 1
  category: 0
  cost: 1000
# Anakin's Starfighter
- guid: 50
  name_id: 81
  description_id: 14
  icon_set_id: 685
  slot: !Equipment None
  item_type: 1
  category: 0
  cost: 4000
  members: true
# Plo Koon's Starfighter
- guid: 51
  name_id: 82
  description_id: 14
  icon_set_id: 687
  slot: !Equipment None
  item_type: 1
  category: 0
  cost: 1000
# Purple Striped Starfighter
- guid: 52
  name_id: 89
  description_id: 14
  icon_set_id: 688
  slot: !Equipment None
  item_type: 1
  category: 0
  cost: 1000
# Green Starfighter
- guid: 53
  name_id: 90
  description_id: 14
  icon_set_id: 686
  slot: !Equipment None
  item_type: 1
  category: 0
  cost: 4000
  members: true
# Terra Green Starfighter
- guid: 748
  name_id: 14062
  description_id: 14063
  icon_set_id: 691
  slot: !Equipment None
  item_type: 1
  category: 0
  cost: 4000
  members: true
# Gold Jedi Starfighter
- guid: 1384
  name_id: 1979
  description_id: 14
  icon_set_id: 1594
  slot: !Equipment None
  item_type: 1
  category: 0
# Red Y-Wing
- guid: 2206
  name_id: 20399
  description_id: 14
  icon_set_id: 1502
  slot: !Equipment None
  item_type: 1
  category: 0
  cost: 1000
# Purple Y-Wing
- guid: 2207
  name_id: 20400
  description_id: 14
  icon_set_id: 1503
  slot: !Equipment None
  item_type: 1
  category: 0
  cost: 1000
# Adi Gallia's Starfighter
- guid: 2709
  name_id: 43213
  description_id: 14
  icon_set_id: 1796
  slot: !Equipment None
  item_type: 1
  category: 0
  cost: 2000
# Saesee Tiin's Starfighter
- guid: 2710
  name_id: 43214
  description_id: 14
  icon_set_id: 1795
  slot: !Equipment None
  item_type: 1
  category: 0
  cost: 2000
# Blue Y-Wing
- guid: 3097
  name_id: 4285
  description_id: 14
  icon_set_id: 2400
  slot: !Equipment None
  item_type: 1
  category: 0
  cost: 4000
  members: true
# Green Y-Wing
- guid: 3098
  name_id: 4286
  description_id: 14
  icon_set_id: 2401
  slot: !Equipment None
  item_type: 1
  category: 0
  cost: 4000
  members: true
# Striped Red Y-Wing
- guid: 3099
  name_id: 4287
  description_id: 14
  icon_set_id: 2402
  slot: !Equipment None
  item_type: 1
  category: 0
  cost: 4000
  members: true
