---
duel_coruscant_hangar_singleplayer:
  ambient_npcs:
    obi-wan_kenobi:
      model_id: 105
      name_id: 1132
      show_name: false
      pos:
        x: 256.05
        y: 50.815445
        z: 219.4
        w: 1.0
      rot:
        x: -0.58
        y: 0
        z: 0.82
        w: 0
      stand_animation_id: 2201
    captain_rex:
      model_id: 2056
      name_id: 6331
      show_name: false
      pos:
        x: 256.0
        y: 51.0256
        z: 217.5
        w: 1.0
      rot:
        x: 0.35
        y: 0
        z: -0.9
        w: 0
      stand_animation_id: 2527
