---
duel_coruscant_hangar_singleplayer:
  ambient_npcs:
    obi-wan_kenobi:
      model_id: 105
      name_id: 1132
      show_name: false
      pos:
        x: 256.05
        y: 50.815445
        z: 219.4
        w: 1.0
      rot:
        x: -0.58
        y: 0
        z: 0.82
        w: 0
      stand_animation_id: 2201
    captain_rex:
      model_id: 2056
      name_id: 6331
      show_name: false
      pos:
        x: 256.0
        y: 51.0256
        z: 217.5
        w: 1.0
      rot:
        x: 0.35
        y: 0
        z: -0.9
        w: 0
      stand_animation_id: 2527
    republic_gunship:
      model_id: 197
      scale: 0.5
      pos:
        x: 282.78
        y: 93.32988
        z: 157.1319
        w: 1.0
      rot:
        x: 0
        y: 0
        z: 0
        w: 0
      is_spawned: false
      enable_gravity: false
      tickable_procedures:
        spawn:
          weight: 36
          steps:
            - spawned_state: OnFirstStepTick
              rail_id: 1046
              composite_effect_id: 1916
              min_duration_millis: 10000
          next_possible_procedures:
            - procedure: remove
        remove:
          steps:
            - spawned_state: Despawn
              min_duration_millis: 1000
          next_possible_procedures:
            - procedure: spawn
            - procedure: empty
              weight: 1259
        empty:
          weight: 1259
          steps:
            - min_duration_millis: 1000
          next_possible_procedures:
            - procedure: spawn
              weight: 36
            - procedure: empty
              weight: 1259
